default: &default
  github_key: <%= ENV["GITHUB_KEY"] %>
  github_secret: <%= ENV["GITHUB_SECRET"] %>

development:
  <<: *default
  secret_key_base: 9f3b83705d48484435a84e16ac7f7eed41a58e1c178aa495f58b86c676470381b242ea96def8023e17fa3309bdd4debfd8c6f9b3ffad8ab8f9aac5c1cde98b11

test:
  <<: *default
  secret_key_base: d5be25e3f191a76ce1f962f834f697fc55c3c7e953656422ef49502ccf76832db7cd0d2f5600a575c26a0d3ec0a04a300345bc11cab6323abf2fa5d846ed4b7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
